#!/bin/bash
sudo apt-get update
sudo apt-get install python3 python3-pip wget git cron default-jre firefox-esr --yes
wget http://tardis.tiny-vps.com/aarm/packages/g/geckodriver/geckodriver-0.23.0-1-aarch64.pkg.tar.xz
wget https://github.com/AsamK/signal-cli/releases/download/v0.6.3/signal-cli-0.6.3.tar.gz
tar zxvf signal-cli-0.6.3.tar.gz
cp signal-cli-0.6.3/bin/* /usr/bin/
cp signal-cli-0.6.3/lib/* /usr/lib/
tar xJf geckodriver-0.23.0-1-aarch64.pkg.tar.xz
cp usr/bin/geckodriver /usr/local/bin/
